map:
  name: 'Austin'
  line: 'centerline'
  delimiter: ','

max_epochs: 10000
max_steps: 1000000
batch_size: 128
lr_actor: 1e-5
lr_critic: 1e-5
alpha: 0.2
tau: 5e-3
gamma: 0.99
replay_size: 1000000
warm_start_steps: 1000
episode_length: 200
